table Channel
	lineageTag: 925e91a9-859b-47ba-90fb-fcfc2c768998

	column ChannelKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8979635e-c4ab-413f-ad57-2d6aa786745a
		summarizeBy: none
		sourceColumn: ChannelKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 3d01de69-45be-4451-ade1-5b9de779f555
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column ChannelDescription
		dataType: string
		lineageTag: 204a0214-4718-4ea3-b92c-96a441d801b1
		summarizeBy: none
		sourceColumn: ChannelDescription

		annotation SummarizationSetBy = Automatic

	partition Channel = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = #"Source Data",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "DimChannel.csv")),
				    Content = #"Filtered Rows"{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ChannelKey", Int64.Type}, {"Channel", type text}, {"ChannelDescription", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

