table Traffic
	lineageTag: ae5d360e-cd69-434f-a9ca-688823896665

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a2a98ec6-e928-4df3-9eff-aceb4727ebbd
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RegionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 20c1dd67-d2e6-4c92-838a-e5a8528e716f
		summarizeBy: none
		sourceColumn: RegionKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ChannelKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a2085e50-1aae-4d29-8c42-c71573b20339
		summarizeBy: none
		sourceColumn: ChannelKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sessions
		dataType: int64
		formatString: 0
		lineageTag: c3efe3f2-6e8a-4847-92b0-7c53b3d06be6
		summarizeBy: sum
		sourceColumn: Sessions

		annotation SummarizationSetBy = Automatic

	column AddToCart
		dataType: int64
		formatString: 0
		lineageTag: 25843d89-1d2e-4fb4-be77-54573bda5837
		summarizeBy: sum
		sourceColumn: AddToCart

		annotation SummarizationSetBy = Automatic

	column Conversions
		dataType: int64
		formatString: 0
		lineageTag: 47cb66f5-0ead-4e62-8f6e-b58834e37316
		summarizeBy: sum
		sourceColumn: Conversions

		annotation SummarizationSetBy = Automatic

	column BounceRate
		dataType: double
		lineageTag: f6111b68-80de-4fb2-a2b5-e8e555e1407b
		summarizeBy: sum
		sourceColumn: BounceRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Traffic = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = #"Source Data",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "FactTraffic.csv")),
				    Content = #"Filtered Rows"{0}[Content],
				    #"Imported CSV" = Csv.Document(Content,[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"RegionKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"Sessions", Int64.Type}, {"AddToCart", Int64.Type}, {"Conversions", Int64.Type}, {"BounceRate", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

